#!/usr/bin/env node
// Builds the translation tables used by the package and the sample app.
// The source strings live in the strings.xml files of the NFCLocatorAndroid repo (nine locales).
//   extract  regenerate src/i18n/generated.ts in the package and the sample app
//   check    verify every locale has exactly the English keys and placeholders and, when the
//            NFCLocatorAndroid checkout is present, that the committed tables are up to date
// The checkout location comes from NFC_LOCATOR_ANDROID_REPO (default: a sibling directory).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const androidRepo =
  process.env.NFC_LOCATOR_ANDROID_REPO ?? path.resolve(root, '../../Android/NFCLocatorAndroid');

const LOCALES = { en: '', es: '-es', 'pt-BR': '-pt-rBR', fr: '-fr', de: '-de', hi: '-hi', ja: '-ja', ko: '-ko', 'zh-CN': '-zh-rCN' };

const TARGETS = [
  {
    name: 'library',
    resDir: path.join(androidRepo, 'nfc-locator-core/src/main/res'),
    out: path.join(root, 'packages/react-native-nfc-locator/src/i18n/generated.ts'),
    exportName: 'LIBRARY_STRINGS',
    keyType: 'LibraryStringKey',
  },
  {
    name: 'sample app',
    resDir: path.join(androidRepo, 'app/src/main/res'),
    out: path.join(root, 'apps/tapsense/src/i18n/generated.ts'),
    exportName: 'APP_STRINGS',
    keyType: 'AppStringKey',
  },
];

function unescapeAndroid(s) {
  return s
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, '&')
    .replace(/\\u([0-9a-fA-F]{4})/g, (_, h) => String.fromCharCode(parseInt(h, 16)))
    .replace(/\\(['"@?\\])/g, '$1')
    .replace(/\\n/g, '\n')
    .replace(/\\t/g, '\t');
}

function parseStrings(file) {
  const xml = fs.readFileSync(file, 'utf8').replace(/<!--[\s\S]*?-->/g, '');
  const map = {};
  const re = /<string\s+([^>]*?)>([\s\S]*?)<\/string>/g;
  let m;
  while ((m = re.exec(xml))) {
    const name = /name="([^"]+)"/.exec(m[1])[1];
    if (/translatable="false"/.test(m[1])) continue; // brand names etc. are not localized
    map[name] = unescapeAndroid(m[2].trim());
  }
  return map;
}

function load(target) {
  const out = {};
  for (const [tag, suffix] of Object.entries(LOCALES)) {
    const file = path.join(target.resDir, `values${suffix}`, 'strings.xml');
    if (!fs.existsSync(file)) throw new Error(`Missing ${file}`);
    out[tag] = parseStrings(file);
  }
  return out;
}

const placeholders = (s) => (s.match(/%\d+\$[sd]/g) ?? []).sort().join(',');

function render(target, data) {
  const header = `// Generated by scripts/i18n.mjs. Do not edit by hand.\n`;
  const keys = Object.keys(data.en).map((k) => `  | '${k}'`).join('\n');
  return `${header}export const ${target.exportName}: Record<string, Record<string, string>> = ${JSON.stringify(data, null, 2)};\n\nexport type ${target.keyType} =\n${keys};\n`;
}

function verify(target, data) {
  const problems = [];
  const en = data.en;
  for (const [tag, strings] of Object.entries(data)) {
    if (tag === 'en') continue;
    for (const key of Object.keys(en)) {
      if (!(key in strings)) problems.push(`[${target.name}] ${tag}: MissingTranslation ${key}`);
      else if (placeholders(strings[key]) !== placeholders(en[key]))
        problems.push(`[${target.name}] ${tag}: StringFormatMatches ${key} (${placeholders(strings[key])} vs ${placeholders(en[key])})`);
    }
    for (const key of Object.keys(strings)) if (!(key in en)) problems.push(`[${target.name}] ${tag}: ExtraTranslation ${key}`);
  }
  return problems;
}

/** Reads the tables back out of a committed generated file (used when the source repo is absent). */
function loadCommitted(target) {
  if (!fs.existsSync(target.out)) throw new Error(`Missing ${target.out}; run: node scripts/i18n.mjs extract`);
  const text = fs.readFileSync(target.out, 'utf8');
  const start = text.indexOf('= ') + 2;
  const end = text.indexOf(';\n\nexport type');
  return JSON.parse(text.slice(start, end));
}

const cmd = process.argv[2];
if (cmd !== 'extract' && cmd !== 'check') {
  console.error('usage: i18n.mjs extract|check');
  process.exit(2);
}
let failed = false;
for (const target of TARGETS) {
  const sourceAvailable = fs.existsSync(target.resDir);
  if (cmd === 'extract' && !sourceAvailable) {
    console.error(`[${target.name}] strings not found at ${target.resDir}; set NFC_LOCATOR_ANDROID_REPO`);
    process.exit(1);
  }
  if (cmd === 'check' && !sourceAvailable) console.warn(`[${target.name}] NFCLocatorAndroid checkout not found; checking committed tables only`);
  const data = sourceAvailable ? load(target) : loadCommitted(target);
  const problems = verify(target, data);
  problems.forEach((p) => console.error(p));
  if (problems.length) failed = true;
  const rendered = render(target, data);
  if (cmd === 'extract') {
    fs.mkdirSync(path.dirname(target.out), { recursive: true });
    fs.writeFileSync(target.out, rendered);
    console.log(`wrote ${path.relative(root, target.out)} (${Object.keys(data.en).length} keys x ${Object.keys(data).length} locales)`);
  } else if (sourceAvailable) {
    const committed = fs.existsSync(target.out) ? fs.readFileSync(target.out, 'utf8') : null;
    if (committed !== rendered) {
      console.error(`[${target.name}] ${path.relative(root, target.out)} is out of date; run: node scripts/i18n.mjs extract`);
      failed = true;
    }
  }
}
process.exit(failed ? 1 : 0);
