#!/usr/bin/env node
// Keeps the bundled seed catalog identical to the one in the NFCLocatorAndroid repo.
//   sync   copy that file into the package and regenerate seedCatalogData.ts
//   check  fail if the generated TS is stale or the catalog shape is invalid, and, when the
//          NFCLocatorAndroid checkout is present, if the package copy differs from its file
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = path.join(root, 'packages/react-native-nfc-locator');
const asset = path.join(pkg, 'assets/seed_catalog.json');
const generated = path.join(pkg, 'src/data/seed/seedCatalogData.ts');
const androidRepo = process.env.NFC_LOCATOR_ANDROID_REPO ?? path.resolve(root, '../../Android/NFCLocatorAndroid');
const androidSeed = path.join(androidRepo, 'nfc-locator-core/src/main/assets/nfc_locator/seed_catalog.json');

const FORM_FACTORS = ['BAR', 'FOLD_BOOK', 'FOLD_FLIP', 'TABLET'];
const REQUIRED = ['manufacturer', 'model', 'formFactor', 'silhouetteTemplateId', 'zoneX', 'zoneY', 'zoneWidth', 'zoneHeight', 'catalogVersion'];
const ALLOWED = new Set([...REQUIRED, 'lastVerifiedAtEpochMs', 'aspectRatio', 'verified']);

function render(json) {
  return `// GENERATED by scripts/seed.mjs from assets/seed_catalog.json. Do not edit by hand;
// a unit test asserts this deep-equals the JSON asset.
import type { SeedCatalogDto } from '../remote/dto';

export const SEED_CATALOG_DATA: SeedCatalogDto = ${JSON.stringify(json, null, 2)};
`;
}

function validateShape(json) {
  const problems = [];
  if (typeof json.catalogVersion !== 'number') problems.push('catalogVersion missing');
  if (!Array.isArray(json.entries)) return [...problems, 'entries missing'];
  json.entries.forEach((e, i) => {
    for (const k of REQUIRED) if (!(k in e)) problems.push(`entry ${i}: missing ${k}`);
    for (const k of Object.keys(e)) if (!ALLOWED.has(k)) problems.push(`entry ${i}: unknown field ${k}`);
    if (!FORM_FACTORS.includes(e.formFactor)) problems.push(`entry ${i}: bad formFactor ${e.formFactor}`);
  });
  return problems;
}

const cmd = process.argv[2];
if (cmd === 'sync') {
  fs.copyFileSync(androidSeed, asset);
  fs.writeFileSync(generated, render(JSON.parse(fs.readFileSync(asset, 'utf8'))));
  console.log('seed catalog synced');
} else if (cmd === 'check') {
  const problems = [];
  const json = JSON.parse(fs.readFileSync(asset, 'utf8'));
  problems.push(...validateShape(json));
  if (fs.existsSync(androidSeed)) {
    if (!fs.readFileSync(asset).equals(fs.readFileSync(androidSeed))) problems.push('assets/seed_catalog.json differs from the NFCLocatorAndroid copy');
  } else console.warn('NFCLocatorAndroid checkout not found; skipping the comparison');
  if (!fs.existsSync(generated) || fs.readFileSync(generated, 'utf8') !== render(json)) problems.push('seedCatalogData.ts is stale; run: node scripts/seed.mjs sync');
  problems.forEach((p) => console.error(p));
  process.exit(problems.length ? 1 : 0);
} else {
  console.error('usage: seed.mjs sync|check');
  process.exit(2);
}
